name = "riannahs-plants-api"
main = "src/index.js"
compatibility_date = "2026-02-27"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "riannahs-plants-dev"
database_id = "c5e6c793-75df-4795-851c-a40b53af3699"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "riannahs-plants-prod"
database_id = "2fe68ad9-15b1-40b3-a1da-00d18c502a72"
